#!/bin/bash

CONFIGDIR=$HOME/.config/


cd $CONFIGDIR


if [ ! -d .git ]; then
	git init
	git add .
	git commit -m "initial autocommit"
fi


usage()
{
	cat <<EOT
Small tool to keep your \$HOME/.config/ under control. Configure this as a cron
job in some way like this:

0 0 * * * $HOME/bin/confkeeper -c

Usage: $0 -c
EOT
}


cron()
{
	# Add new and changed files..
	git add --all .
	git commit -m "daily autocommit"
	git gc
}


while getopts "hvc" opt; do
	case $opt in
		h)
			usage
			;;
		v)
			set -x
			;;
		c)
			cron
			;;
		\?)
			usage
			;;
  esac
done
