#!/bin/sh

#       sticksync
#
#       (C) Copyright 2017 by Dominic Hopf <dmaphy@googlemail.com>
#       Version: 1.0.1
#       Last Change: 2017-07-15

BACKUPDIR=$HOME/backups/
MEDIAPATH=/run/media/dmaphy/

usage() {
cat <<EOF
Usage: $0 <name>

Where <name> is one of 1GSTICK or 8GSTICK.
EOF
exit 1;
}

if [ -z "$@" ]; then
	usage
fi

if [ ! -d $BACKUPDIR$@ ]; then
	mkdir -p $BACKUPDIR$@
fi

if [ ! -d $MEDIAPATH$@  ]; then
	echo -e "Could not find $MEDIAPATH$@.\nExiting.\n"
	exit 1
fi

rsync -avrulp --delete $MEDIAPATH$@/ $BACKUPDIR$@/
